#!/bin/sh


case "$1" in
    start)
        echo "Starting pm25 app"
        start-stop-daemon -S --bacground -n pm25app --startas /usr/bin/pm25_app.py
        ;;
    stop)
        echo "Stopping pm25 app"
        start-stop-daemon -K -n pm25app
        ;;
    *)
        echo "Usage: %0 {start|stop}"
    exit 1
esac

exit 0   